language: go

go:
    - 1.7.x

script:
    - git --version
    # To run tests while developing, use 'go test ./...'
    - ./code-coverage.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)